//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonashBnBv3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image
    {
        public int imageId { get; set; }
        public string imagePath { get; set; }
        public string imageName { get; set; }
        public Nullable<int> hotelId { get; set; }
    
        public virtual Hotel Hotel { get; set; }
    }
}
